### ISSUE TITLE
openshift-container8.jcloud.local无法脱取平台本身的镜像

### ISSUE THREAD

**Issue by hank-sunday** [asiainfoLDP/datafoundry-troubleshooting#26]
{kubelet openshift-container8.jcloud.local}	spec.containers{sentinel}	Warning		Failed		Failed to pull image "172.30.188.59:5000/service-broker/redis-openshift-orchestration": Error while pulling image: Get http://172.30.188.59:5000/v1/repositories/service-broker/redis-openshift-orchestration/images: dial tcp 172.30.188.59:5000: no route to host

同时启动的其他pod可以拖取，比如下面这个：
{kubelet openshift-container3.jcloud.local}	spec.containers{sentinel}	Normal		Pulling		pulling image "172.30.188.59:5000/service-broker/redis-openshift-orchestration"

**Comment by hank-sunday** [comment]
同样的问题，还存在：
Node:		openshift-container-add3/192.168.12.20
Node:		openshift-container-add2/192.168.12.19
Node:		openshift-container8.jcloud.local/192.168.12.25

**Comment by dragon9783** [comment]
Fixed, base on my  experiment ,docker service must restart after upgrade openvswitch .

Jeddy Liu
Best Regards
