### ISSUE TITLE
［京东环境］build过程中默认去拖取aws的镜像

### ISSUE THREAD

**Issue by hank-sunday** [asiainfoLDP/datafoundry-troubleshooting#27]
Step 1 : FROM redis@sha256:6abf21819a654f918119d6ee1ccacafc94247d6f417be748501d88782bbb8845
Trying to pull repository docker-registry-default.app.asiainfodata.com/redis ... failed

这个不应该这样，因为默认去registry.dataos.io的库，否则私有库不能拖到。

节点是：
kubelet openshift-container3.jcloud.local

**Comment by dragon9783** [comment]
Remove docker daemon options --add-registry will fix , registry.dataos.io also authorized by credentials, so have same issue when docker daemon registry token expired.

Jeddy Liu
Best Regards

**Comment by lixwlixw** [comment]
把/etc/sysconfig/docker里面的 ADD_REGISTRY='docker-registry-default.app.asiainfodata.com' 改为ADD_REGISTRY='--add-registry registry.dataos.io'
