### ISSUE TITLE
[京东环境]BUILD出错  TeardownNetworkError: "Failed to teardown network for pod   using network plugins \"redhat/openshift-ovs-subnet\

### ISSUE THREAD

**Issue by hank-sunday** [asiainfoLDP/datafoundry-troubleshooting#29]
Name:		zookeeper-openshift-orchestration-2-build
Namespace:	service-broker
Image(s):	registry.dataos.io/openshift/origin-docker-builder:abcdef
Node:		openshift-container5.jcloud.local/192.168.12.22
Start Time:	Sun, 17 Apr 2016 11:36:00 +0800
Labels:		openshift.io/build.name=zookeeper-openshift-orchestration-2
Status:		Failed
Reason:		
Message:	
IP:		10.1.5.3
Controllers:	<none>
Containers:
  docker-build:
    Container ID:	docker://a1ef62633696ed3ef6dbfea1ad19d514fdf57514da166c3b2f11a7eec2b3274e
    Image:		registry.dataos.io/openshift/origin-docker-builder:abcdef
    Image ID:		docker://ee03496dff2c058e1e0edafa1e365901c3ba88260f40e6131c3e6e56e9e448ed
    Args:
      --loglevel=4
    QoS Tier:
      cpu:		BestEffort
      memory:		BestEffort
    State:		Terminated
      Reason:		Error
      Exit Code:	255
      Started:		Sun, 17 Apr 2016 11:36:02 +0800
      Finished:		Sun, 17 Apr 2016 11:36:18 +0800
    Ready:		False
    Restart Count:	0
    Environment Variables:
      BUILD:	{"kind":"Build","apiVersion":"v1","metadata":{"name":"zookeeper-openshift-orchestration-2","namespace":"service-broker","selfLink":"/oapi/v1/namespaces/service-broker/builds/zookeeper-openshift-orchestration-2","uid":"801c835a-044d-11e6-aa04-fa163d0e0615","resourceVersion":"663136","creationTimestamp":"2016-04-17T03:35:58Z","labels":{"build":"zookeeper-openshift-orchestration","buildconfig":"zookeeper-openshift-orchestration","openshift.io/build-config.name":"zookeeper-openshift-orchestration"},"annotations":{"openshift.io/build.number":"2"}},"spec":{"serviceAccount":"builder","source":{"type":"Git","git":{"uri":"https://github.com/asiainfoLDP/zookeeper-openshift-orchestration.git"},"contextDir":"image","secrets":[]},"strategy":{"type":"Docker","dockerStrategy":{"from":{"kind":"DockerImage","name":"develar/java@sha256:7101301b21c47201b5c633f20341a08c6051a210e3d123abe157efb1081fbb30"}}},"output":{"to":{"kind":"DockerImage","name":"172.30.188.59:5000/service-broker/zookeeper-openshift-orchestration:latest"},"pushSecret":{"name":"builder-dockercfg-mddyg"}},"resources":{},"postCommit":{}},"status":{"phase":"New","outputDockerImageReference":"172.30.188.59:5000/service-broker/zookeeper-openshift-orchestration:latest","config":{"kind":"BuildConfig","namespace":"service-broker","name":"zookeeper-openshift-orchestration"}}}

      BUILD_LOGLEVEL:		4
      SOURCE_REPOSITORY:	https://github.com/asiainfoLDP/zookeeper-openshift-orchestration.git
      SOURCE_URI:		https://github.com/asiainfoLDP/zookeeper-openshift-orchestration.git
      SOURCE_CONTEXT_DIR:	image
      ORIGIN_VERSION:		v1.1.6-ldp0.3
      PUSH_DOCKERCFG_PATH:	/var/run/secrets/openshift.io/push
Conditions:
  Type		Status
  Ready 	False 
Volumes:
  docker-socket:
    Type:	HostPath (bare host directory volume)
    Path:	/var/run/docker.sock
  builder-dockercfg-mddyg-push:
    Type:	Secret (a secret that should populate this volume)
    SecretName:	builder-dockercfg-mddyg
  builder-token-8ddwf:
    Type:	Secret (a secret that should populate this volume)
    SecretName:	builder-token-8ddwf
Events:
  FirstSeen	LastSeen	Count	From						SubobjectPath			Type		Reason		Message
  ---------	--------	-----	----						-------------			--------	------		-------
  2m		2m		1	{default-scheduler }								Normal		Scheduled	Successfully assigned zookeeper-openshift-orchestration-2-build to openshift-container5.jcloud.local
  2m		2m		1	{kubelet openshift-container5.jcloud.local}	spec.containers{docker-build}	Normal		Pulled		Container image "registry.dataos.io/openshift/origin-docker-builder:abcdef" already present on machine
  2m		2m		1	{kubelet openshift-container5.jcloud.local}	spec.containers{docker-build}	Normal		Created		Created container with docker id a1ef62633696
  2m		2m		1	{kubelet openshift-container5.jcloud.local}	spec.containers{docker-build}	Normal		Started		Started container with docker id a1ef62633696
  2m		2m		1	{kubelet openshift-container5.jcloud.local}					Warning		FailedSync	Error syncing pod, skipping: failed to "TeardownNetwork" for "zookeeper-openshift-orchestration-2-build_service-broker" with TeardownNetworkError: "Failed to teardown network for pod \"802027b3-044d-11e6-aa04-fa163d0e0615\" using network plugins \"redhat/openshift-ovs-subnet\": exit status 1"

**Comment by yepengxj** [comment]
ovsbug
https://github.com/openshift/origin/issues/8450
