### ISSUE TITLE
[京东环境]dns解析错误，无法解析服务的短名字（长名字可以解析），aws环境可以

### ISSUE THREAD

**Issue by hank-sunday** [asiainfoLDP/datafoundry-troubleshooting#30]
/opt/zookeeper # ping sb-instanceid-zk
ping: bad address 'sb-instanceid-zk'
/opt/zookeeper # cd /etc
/etc # cat re*
search service-broker.svc.cluster.local svc.cluster.local cluster.local jcloud.local
nameserver 172.30.0.1
nameserver 192.168.12.11
nameserver 192.168.12.2
options ndots:5
/etc # nslookup
BusyBox v1.24.1 (2015-12-16 08:00:02 GMT) multi-call binary.

Usage: nslookup [HOST] [SERVER]

Query the nameserver for the IP address of the given HOST
optionally using a specified DNS server
/etc # nslookup sb-instanceid-zk 
nslookup: can't resolve '(null)': Name does not resolve

nslookup: can't resolve 'sb-instanceid-zk': Name does not resolve
/etc # nslookup sb-instanceid-zk  172.30.0.1
Server:    172.30.0.1
Address 1: 172.30.0.1 kubernetes.default.svc.cluster.local

nslookup: can't resolve 'sb-instanceid-zk': Name does not resolve

/etc # nslookup sb-instanceid-zk.service-broker.svc.cluster.local
nslookup: can't resolve '(null)': Name does not resolve

Name:      sb-instanceid-zk.service-broker.svc.cluster.local
Address 1: 172.30.45.218 sb-instanceid-zk.service-broker.svc.cluster.local

**Comment by dragon9783** [comment]
FYI
https://github.com/openshift/origin/issues/8556

**Comment by yepengxj** [comment]
alpine镜像的dns机制问题，通过ubuntu测试正常
