### ISSUE TITLE
openshift-container2.jcloud.local 无法执行pod任务

### ISSUE THREAD

**Issue by hank-sunday** [asiainfoLDP/datafoundry-troubleshooting#35]
HeHankdeMacBook-Pro:docker-storm-cluster Hank$ oc describe pod apache-storm-nimbus-pu7iw 
Name:		apache-storm-nimbus-pu7iw
Namespace:	service-broker
Image(s):	172.30.188.59:5000/service-broker/docker-storm-cluster
Node:		openshift-container2.jcloud.local/192.168.12.24
Start Time:	Thu, 21 Apr 2016 21:59:53 +0800
Labels:		app=storm,storm=nimbus
Status:		Pending
Reason:		
Message:	
IP:		
Controllers:	ReplicationController/apache-storm-nimbus
Containers:
  zookeeper:
    Container ID:	
    Image:		172.30.188.59:5000/service-broker/docker-storm-cluster
    Image ID:		
    Port:		
    QoS Tier:
      cpu:		BestEffort
      memory:		BestEffort
    State:		Waiting
      Reason:		ContainerCreating
    Ready:		False
    Restart Count:	0
    Environment Variables:
      CONFIGURE_ZOOKEEPER:	true
      STORM_CMD:		nimbus
      ZK_SERVER_1_SERVICE_HOST:	zookeeper
Conditions:
  Type		Status
  Ready 	False 
Volumes:
  storm-data:
    Type:	EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:	
  default-token-xpo6i:
    Type:	Secret (a secret that should populate this volume)
    SecretName:	default-token-xpo6i
Events:
  FirstSeen	LastSeen	Count	From			SubobjectPath	Type		Reason		Message
  ---------	--------	-----	----			-------------	--------	------		-------
  4m		4m		1	{default-scheduler }			Normal		Scheduled	Successfully assigned apache-storm-nimbus-pu7iw to openshift-container2.jcloud.local

调度过去，无法执行，估计是docker挂了。看看原因，补上监控。

**Comment by hank-sunday** [comment]
Events:
  FirstSeen	LastSeen	Count	From			SubobjectPath	Type		Reason		Message
  ---------	--------	-----	----			-------------	--------	------		-------
  1m		1m		1	{default-scheduler }			Normal		Scheduled	Successfully assigned apache-storm-supervisor-3m8pj to openshift-container-add3

这个也很慢。

**Comment by yepengxj** [comment]
监控已在测试中
