### ISSUE TITLE
从 stry.dataos.io/wurstmeister/kafka拖取镜像？

### ISSUE THREAD

**Issue by hank-sunday** [asiainfoLDP/datafoundry-troubleshooting#36]
Step 1 : FROM wurstmeister/kafka@sha256:79d959e62659ecdf14cb9afac73f834c11637a286692ba3626dd675c2ef0c79e
Trying to pull repository stry.dataos.io/wurstmeister/kafka ... failed
Trying to pull repository docker.io/wurstmeister/kafka ... Pulling from wurstmeister/kafka

**Comment by yepengxj** [comment]
需修改node docker配置
