### ISSUE TITLE
openshift-container-add1.jcloud.local 的docker add-regsitry配置不对

### ISSUE THREAD

**Issue by hank-sunday** [asiainfoLDP/datafoundry-troubleshooting#38]
最好有一个程序可以核对配置。
Step 1 : FROM google/debian@sha256:dcf93b5a7c21824463bd99d21032f1955c9fa271bd1bb5ec2a11acfe840d18fd
Trying to pull repository stry.dataos.io/google/debian ... failed
Trying to pull repository docker.io/google/debian ... Pulling from google/debian

**Comment by zhangzhaorui** [comment]
修改/etc/sysconfig/docker重启docker
